/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PruebasFrame;

import java.awt.Component;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import pruebagit.Cuenta;

/**
 *
 * @author Mariam
 */
public class CajeroPrincipal extends javax.swing.JFrame {

    public static ArrayList<Cuenta> Cuentas = new ArrayList<Cuenta>();
    public static JTextField caja;
    //panelInteraction maneja los paneles
    private int panelInteraction = 0;
    //deposito //tambien se puede usar para retiro  
    float cantidad;

    //boton hilo es para que se duerma por 1 segundo 5 veces.
    private BotonHilo bh;
    public static int correctAccount = 123;
    Cuenta uno;

    /**
     * Creates new form pruebaFrame
     */
    public CajeroPrincipal() {
        initComponents();
        int id=123;
        //ABRE PANEL NUM 0 QUE ES LOGIN
        manage_window(new Login());

        try {
            //Cambia el Look And Feel de la aplicación de Java a Nimbus
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Error cambiando el Look And Feel
            javax.swing.JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        } catch (InstantiationException ex) {
            //Error cambiando el Look And Feel
            javax.swing.JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        } catch (IllegalAccessException ex) {
            //Error cambiando el Look And Feel
            javax.swing.JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        } catch (UnsupportedLookAndFeelException ex) {
            //Error cambiando el Look And Feel
            javax.swing.JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        
         id = id+3;
        uno = new Cuenta(id, "Roberto", 123, 100, 1000);
        try {
            FileInputStream fi = new FileInputStream("Cuentas.dat");
            ObjectInputStream oi = new ObjectInputStream(fi);
            Cuentas = (ArrayList) oi.readObject();
            oi.close();
        } catch (Exception exception) {
            System.out.println("Error -- " + exception.toString());
            System.out.println("Error no se ha creado el archivo ");
        }
        Cuentas.add(uno);
        try {
            FileOutputStream fo = new FileOutputStream("Cuentas.dat");
            ObjectOutputStream oo = new ObjectOutputStream(fo);
            oo.writeObject(Cuentas);
            oo.flush();
            oo.close();
            System.out.println("Vector almacenado en archivo");
        } catch (IOException exception) {
            System.out.println("Error -- " + exception.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        btnRetira = new javax.swing.JButton();
        btnDeposita = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1078, 296));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("0");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("4");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("5");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("6");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("7");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("8");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("9");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnEnter.setBackground(new java.awt.Color(0, 0, 0));
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton14.setText("SALIR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        btnRetira.setText("RETIRA");

        btnDeposita.setText("DEPOSITA");
        btnDeposita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRetira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeposita, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRetira))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnDeposita)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        desktop.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1078, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(desktop)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, 293, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//boton teclado 1
        caja.setText(caja.getText() + "1");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
//botonEnter 
        enterAction();
        /*        panelAcceso.removeAll();
         // m1.setVisible(true);
         panelAcceso.add(m1);
         panelAcceso.validate();
         panelAcceso.repaint();
         panelAcceso.updateUI();
         m1.setSize(panelAcceso.getPreferredSize());
         m1.setVisible(true);
         //m1.setVisible(true);
        
        
         */

    }//GEN-LAST:event_btnEnterActionPerformed

    private void enterAction() {

        //estamos en login 
        if (panelInteraction == 0) {

            String vacio1 = Login.txtnum.getText();
            char[] vacio2 = Login.txtnip.getPassword();
            if (vacio1.length() < 1 || vacio2.length < 1) {

                JOptionPane.showMessageDialog(null, "No puede dejar algun campo vacio para accesar", "Error de captura", JOptionPane.ERROR_MESSAGE);

            } else {

                int account = Integer.parseInt(Login.txtnum.getText()); //Agarra texto del txtCuenta
                int correctAccount = 123; //Numero de cuenta correcto // esto se cambiara por un for cuando este el archivo
                int admin = 456;
                char[] adminpas = {'4', '5', '6'};
                char[] input = Login.txtnip.getPassword(); //agarra el texto que se puso en nip
                char[] correctPassword = {'1', '2', '3'}; //este es mi nip correcto //esto se cambiara por un for cuando este el archivo
                boolean isCorrect = false; //si es correcta es true 

                if (account == admin && input.length == adminpas.length) {
                    manage_window(new AltaCuentas());
                    btnAceptar.setEnabled(false);
                    btnCancelar.setEnabled(false);
                    panelInteraction = 5;
                } else {

            //for ////////////////////////////
                    if (account == correctAccount) {
                        System.out.println("CORRECTO ID");
                        isCorrect = false;
                    } else {
                        JOptionPane.showMessageDialog(this, "Su cuenta es incorrecta");
                        isCorrect = true;

                    }

                    if (isCorrect == false) { //verificacontraseña
                        if (input.length != correctPassword.length) {
                            JOptionPane.showMessageDialog(this, "NIP Incorrecto");

                            Login.txtnip.setText("");
                            Login.txtnum.setText("");
                        } else {
                            manage_window(new MenuPrincipal());
                            panelInteraction = 1;

                        }
                    } else {
                        if (isCorrect == true) {
                            Login.txtnip.setText("");
                            Login.txtnum.setText("");
                        }
                    }
                }
            }
        } else {
            //PANEL 1 MENU PRINCIPAL

            if (panelInteraction == 1) {
                String vacio = MenuPrincipal.txtopc.getText();

                if (vacio.length() < 1) {

                    JOptionPane.showMessageDialog(null, "Debe escribir una opcion", "Error de captura", JOptionPane.ERROR_MESSAGE);

                } else {
                    int opc = Integer.parseInt(MenuPrincipal.txtopc.getText());//dame el texto del usuario de la opcion que teclee
                    switch (opc) {
                        case 1:
                            manage_window(new Saldo());
                            panelInteraction = 2;
                            break;
                        case 2:
                            manage_window(new Retiro());
                            panelInteraction = 3;
                            Retiro.txtRetiro.requestFocus();
                            
                            break;
                        case 3:
                            manage_window(new Deposito());
                            panelInteraction = 4;
                            btnRetira.setEnabled(false);
                            btnDeposita.setEnabled(false);


                            break;
                        default:
                            JOptionPane.showMessageDialog(this, "OPCION NO VALIDA, INTENTE DE NUEVO");
                            MenuPrincipal.txtopc.setText("");
                            break;
                    }

                    
                    
                }
                
                
                            

                            
                                //DEPOSITO PANEL
                                if (panelInteraction == 4) {
                                    String vacio1 = Deposito.txtdolares.getText();
                                    String vacio2 = Deposito.txtcentavos.getText();
                                    String vacio3 = Deposito.txtdepositara.getText();
                                    if (vacio1.length() < 1 || vacio2.length() < 1) {
                                        JOptionPane.showMessageDialog(null, "Introduce una cantidad", "Error de captura", JOptionPane.ERROR_MESSAGE);
                                    } else {
                                        if (vacio3.length() < 1) {
                                            JOptionPane.showMessageDialog(null, "Introduce un numero de cuenta a depositar", "Error de captura", JOptionPane.ERROR_MESSAGE);
                                        } else {
                                            btnAceptar.setEnabled(false);

                                            Depositar();

                                        }

                        }
                                    }else{
                    if(panelInteraction==2){
                       
                    }

                                

                        }
                
                         
            }

            
            
        }
        
        
        
    }
    

    private void enterActionR() {

        switch (panelInteraction) {
            case 0:
                int account = Integer.parseInt(Login.txtnum.getText());
                int correctAccount = 123;

                //char[] input = Login.txtnip.getPassword();
                char[] input = Login.txtnip.getPassword();
                char[] correctPassword = {'1', '2', '3'};
                boolean isCorrect = true;
                if (account == correctAccount) {
                    System.out.println("CORRECTO ID");
                    isCorrect = false;
                } else {
                    JOptionPane.showMessageDialog(this, "Su cuenta es incorrecta");
                    isCorrect = true;
                    // Login.txtnum.setText("");
                }

                if (isCorrect == false) { //verificacontraseña
                    if (input.length != correctPassword.length) {
                        JOptionPane.showMessageDialog(this, "NIP Incorrecto");

                        Login.txtnip.setText("");
                        Login.txtnum.setText("");
                    } else {
                        manage_window(new MenuPrincipal());
                        panelInteraction = 1;

                    }
                } else {
                    if (isCorrect == true) {
                        Login.txtnip.setText("");
                        Login.txtnum.setText("");
                    }
                }
                break;
            case 1:

                int opc = Integer.parseInt(MenuPrincipal.txtopc.getText());

                switch (opc) {
                    case 1:
                        manage_window(new Saldo());
                        panelInteraction = 2;

                        break;
                    case 2:
                        manage_window(new Retiro());
                        panelInteraction = 3;

                        break;
                    case 3:
                        manage_window(new Deposito());
                        panelInteraction = 4;
                        btnRetira.setEnabled(false);
                        btnDeposita.setEnabled(false);

                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "OPCION NO VALIDA, INTENTE DE NUEVO");
                        MenuPrincipal.txtopc.setText("");
                        break;
                }

                break;
        }

    }

    private void Depositar() {
        btnDeposita.setEnabled(false);
        int dolares = Integer.parseInt(Deposito.txtdolares.getText());
        float centavos = Float.parseFloat(Deposito.txtcentavos.getText());
        int cuenta = Integer.parseInt(Deposito.txtdepositara.getText());
        centavos = centavos / 100;
        cantidad = dolares + centavos;
        System.out.println(cuenta);
        //for

        if (cuenta == 123) {
            System.out.println("cuenta valida, entonces deposita" + cantidad);
            bh = new BotonHilo(btnDeposita);
            bh.start();

        } else {
            JOptionPane.showMessageDialog(this, "La cuenta a la que intenta depositar NO existe");
            btnAceptar.setEnabled(true);

        }

    }

    private void solicitarSaldo() {

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        caja.setText(caja.getText() + "2");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        caja.setText(caja.getText() + "3");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        caja.setText(caja.getText() + "4");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        caja.setText(caja.getText() + "5");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        caja.setText(caja.getText() + "6");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        caja.setText(caja.getText() + "7");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        caja.setText(caja.getText() + "8");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        caja.setText(caja.getText() + "9");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        caja.setText(caja.getText() + "0");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
//MenuPrincipal m= new MenuPrincipal();
        if (panelInteraction == 1) {
            manage_window(new Login());
            panelInteraction = 0;
        } else {
            if (panelInteraction == 0) {
                System.exit(0);

            } else {
                if (panelInteraction == 2) {
                    manage_window(new MenuPrincipal());
                    panelInteraction = 1;
                } else {
                    if (panelInteraction == 4) {
                        manage_window(new MenuPrincipal());
                        panelInteraction = 1;
                    } else {
                        if (panelInteraction == 3) {
                            manage_window(new MenuPrincipal());
                            panelInteraction = 1;
                        } else {
                            if (panelInteraction == 5) {
                                manage_window(new Login());
                                btnAceptar.setEnabled(true);
                                btnCancelar.setEnabled(true);
                                panelInteraction = 0;

                            }
                        }
                    }

                }
            }

        }
        //System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        enterAction();
        //enterActionR();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Login.txtnip.setText("");
        Login.txtnum.setText("");

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDepositaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositaActionPerformed
        if (bh.isAlive()) {
            bh.interrupt();
            btnDeposita.setEnabled(false);
            javax.swing.JOptionPane.showMessageDialog(null, "Deposito exitoso");
            btnAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_btnDepositaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajeroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajeroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajeroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajeroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CajeroPrincipal().setVisible(true);
            }
        });
    }

    public void manage_window(Component c) {
        desktop.removeAll();
        desktop.setPreferredSize(c.getPreferredSize());
        desktop.add(c);
        desktop.updateUI();
        c.setSize(desktop.getPreferredSize());
        c.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeposita;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnRetira;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
