/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PruebasFrame;


import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import pruebagit.Cuenta;

/**
 *
 * @author Mariam
 */
public class Retiro extends javax.swing.JPanel {
   public static int cantidadARetirar=0;
public static ArrayList<Cuenta> Cuentas = new ArrayList<Cuenta>();
int cuenta = CajeroPrincipal.correctAccount;
 int pos;
    /**
     * Creates new form Retiro
     */
    public Retiro() {
        initComponents();
        
       txtRetiroOtraCantidad.setEnabled(false);
        cantidadARetirar=0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbldeposito = new javax.swing.JLabel();
        txtRetiroOtraCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox100 = new javax.swing.JCheckBox();
        jCheckBox200 = new javax.swing.JCheckBox();
        jCheckBox400 = new javax.swing.JCheckBox();
        jCheckBox800 = new javax.swing.JCheckBox();
        jCheckBox600 = new javax.swing.JCheckBox();
        jCheckBox1000 = new javax.swing.JCheckBox();
        jButtonOtraCantidad = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 153));

        lbldeposito.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbldeposito.setForeground(new java.awt.Color(255, 255, 255));
        lbldeposito.setText("Retiro de la Cuenta");

        txtRetiroOtraCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRetiroOtraCantidadFocusGained(evt);
            }
        });
        txtRetiroOtraCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetiroOtraCantidadActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad a Retirar: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Únicamente cantidades que sean múltiplo de 20.");

        jCheckBox100.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox100.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox100.setText("$ 100");
        jCheckBox100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox100ActionPerformed(evt);
            }
        });

        jCheckBox200.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox200.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox200.setText("$ 200");
        jCheckBox200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox200ActionPerformed(evt);
            }
        });

        jCheckBox400.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox400.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox400.setText("$400");
        jCheckBox400.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox400ActionPerformed(evt);
            }
        });

        jCheckBox800.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox800.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox800.setText("$800");
        jCheckBox800.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox800ActionPerformed(evt);
            }
        });

        jCheckBox600.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox600.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox600.setText("$600");
        jCheckBox600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox600ActionPerformed(evt);
            }
        });

        jCheckBox1000.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1000.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1000.setText("$ 1000");
        jCheckBox1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1000ActionPerformed(evt);
            }
        });

        jButtonOtraCantidad.setText("Desea retirar otra cantidad:");
        jButtonOtraCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtraCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jButtonOtraCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lbldeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel9)
                        .addGap(36, 36, 36)
                        .addComponent(txtRetiroOtraCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox100)
                            .addComponent(jCheckBox200)
                            .addComponent(jCheckBox400))
                        .addGap(406, 406, 406)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1000)
                            .addComponent(jCheckBox600)
                            .addComponent(jCheckBox800))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(443, 443, 443)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(545, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbldeposito)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jCheckBox100)
                        .addGap(29, 29, 29)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox200)
                            .addComponent(jCheckBox800)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox600)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox400)
                    .addComponent(jCheckBox1000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOtraCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRetiroOtraCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
        );
        jDesktopPane1.setLayer(lbldeposito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtRetiroOtraCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBox100, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBox200, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBox400, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBox800, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBox600, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBox1000, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonOtraCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRetiroOtraCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetiroOtraCantidadActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_txtRetiroOtraCantidadActionPerformed

    private void txtRetiroOtraCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRetiroOtraCantidadFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRetiroOtraCantidadFocusGained

    private void jCheckBox100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox100ActionPerformed

    private void jCheckBox800ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox800ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox800ActionPerformed

    private void jCheckBox200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox200ActionPerformed

    private void jCheckBox400ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox400ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox400ActionPerformed

    private void jCheckBox600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox600ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox600ActionPerformed

    private void jCheckBox1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1000ActionPerformed

    private void jButtonOtraCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtraCantidadActionPerformed
        // TODO add your handling code here:
        jCheckBox100.setEnabled(false);
        jCheckBox200.setEnabled(false);
        jCheckBox400.setEnabled(false);
        jCheckBox600.setEnabled(false);
        jCheckBox800.setEnabled(false);
        jCheckBox1000.setEnabled(false);
        
        jCheckBox100.setSelected(false);
        jCheckBox200.setSelected(false);
        jCheckBox400.setSelected(false);
        jCheckBox600.setSelected(false);
        jCheckBox800.setSelected(false);
        jCheckBox1000.setSelected(false);
        txtRetiroOtraCantidad.setEnabled(true);
        txtRetiroOtraCantidad.setEditable(true);
        txtRetiroOtraCantidad.requestFocus();
    }//GEN-LAST:event_jButtonOtraCantidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOtraCantidad;
    protected static javax.swing.JCheckBox jCheckBox100;
    protected static javax.swing.JCheckBox jCheckBox1000;
    protected static javax.swing.JCheckBox jCheckBox200;
    protected static javax.swing.JCheckBox jCheckBox400;
    protected static javax.swing.JCheckBox jCheckBox600;
    protected static javax.swing.JCheckBox jCheckBox800;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbldeposito;
    public static javax.swing.JTextField txtRetiroOtraCantidad;
    // End of variables declaration//GEN-END:variables
private int validarNC(int NC, ArrayList Array) {
        int llave = 0; //Cero significa que no lo ha encontrado uno significa que lo ha encontrado
        int cont =0;
        for (Object cuenta : Array) {
            
                if (((Cuenta) (cuenta)).getNumDeCuenta()==NC) {
                    llave = 1;
                    System.out.println("NSS encontrado");
                    System.out.println("Nombre del NSS encontrado: "
                            + ((Cuenta) (cuenta)).getNumDeCuenta());
                    
                    pos = cont;
                    break;

                }

            
            cont++;
        }
        return llave;
    }

}
