/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PruebasFrame;

/**
 *
 * @author Mariam
 */
public class SaldoR extends javax.swing.JPanel {

    /**
     * Creates new form Deposito
     */
    public SaldoR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbldeposito = new javax.swing.JLabel();
        lblintroduzca = new javax.swing.JLabel();
        txtdolares = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtdepositara = new javax.swing.JTextField();
        txtcentavos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1078, 299));
        setPreferredSize(new java.awt.Dimension(1078, 299));

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 153));
        jDesktopPane1.setToolTipText("");
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1078, 299));

        lbldeposito.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbldeposito.setForeground(new java.awt.Color(255, 255, 255));
        lbldeposito.setText("DEPÓSITO");

        lblintroduzca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblintroduzca.setForeground(new java.awt.Color(255, 255, 255));
        lblintroduzca.setText("Introduzca la cantidad a depósitar");

        txtdolares.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdolaresFocusGained(evt);
            }
        });
        txtdolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdolaresActionPerformed(evt);
            }
        });
        txtdolares.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdolaresKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Introduzca el número de cuenta al cual depositará");

        txtdepositara.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdepositaraFocusGained(evt);
            }
        });
        txtdepositara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepositaraActionPerformed(evt);
            }
        });
        txtdepositara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdepositaraKeyTyped(evt);
            }
        });

        txtcentavos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcentavosActionPerformed(evt);
            }
        });
        txtcentavos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcentavosFocusGained(evt);
            }
        });
        txtcentavos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcentavosKeyTyped(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("dólares");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("centavos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(".");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblintroduzca))
                .addGap(29, 29, 29)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(txtdolares, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcentavos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)))
                        .addContainerGap(376, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtdepositara, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(86, 86, 86))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lbldeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbldeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblintroduzca)
                            .addComponent(txtdolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcentavos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdepositara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(lbldeposito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblintroduzca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtdolares, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtdepositara, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtcentavos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdolaresActionPerformed
CajeroPrincipal.caja = this.txtdolares;             
    }//GEN-LAST:event_txtdolaresActionPerformed

    private void txtdepositaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepositaraActionPerformed
        CajeroPrincipal.caja = this.txtdepositara;   
    }//GEN-LAST:event_txtdepositaraActionPerformed

    private void txtdolaresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdolaresKeyTyped
         char tecla;
      tecla=evt.getKeyChar();
      
      if(Character.isLetter(tecla)){
          evt.consume();
          getToolkit().beep();
      }
    }//GEN-LAST:event_txtdolaresKeyTyped

    private void txtcentavosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcentavosKeyTyped
 char tecla;
      tecla=evt.getKeyChar();
      
      if(Character.isLetter(tecla)){
          evt.consume();
          getToolkit().beep();
      }        // TODO add your handling code here:
    }//GEN-LAST:event_txtcentavosKeyTyped

    private void txtdepositaraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepositaraKeyTyped
 char tecla;
      tecla=evt.getKeyChar();
      
      if(Character.isLetter(tecla)){
          evt.consume();
          getToolkit().beep();
      }        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepositaraKeyTyped

    private void txtdolaresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdolaresFocusGained
CajeroPrincipal.caja = this.txtdolares;   
// TODO add your handling code here:
    }//GEN-LAST:event_txtdolaresFocusGained

    private void txtcentavosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcentavosActionPerformed

        CajeroPrincipal.caja = this.txtcentavos;   
// TODO add your handling code here:
    }//GEN-LAST:event_txtcentavosActionPerformed

    private void txtcentavosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcentavosFocusGained
   CajeroPrincipal.caja = this.txtcentavos;   
    }//GEN-LAST:event_txtcentavosFocusGained

    private void txtdepositaraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdepositaraFocusGained
        CajeroPrincipal.caja = this.txtdepositara;
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepositaraFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbldeposito;
    private javax.swing.JLabel lblintroduzca;
    protected static javax.swing.JTextField txtcentavos;
    protected static javax.swing.JTextField txtdepositara;
    protected static javax.swing.JTextField txtdolares;
    // End of variables declaration//GEN-END:variables
}
